### ISSUE TITLE
Quotes required on IPv6 Source Address

### ISSUE THREAD

**Issue by shrunbr** [checktheroads/hyperglass#130]
Hyperglass build-ui requires "devices.yaml" before it'll build and as part of the the build it only like IPv6 source addresses when they are in quotes. Adding an IPv6 address without quotes or without quotes with CIDR notation it fails. See below.

**Error when building with IPv6 in CIDR notation**
```

[ERROR] 20210329 03:43:12 | hyperglass.configuration.validation:47 | validate_config → 1 validation error for Device
vrfs -> ipv6 -> source_address
  value is not a valid IPv6 address (type=value_error.ipv6address)
[ERROR] 20210329 03:43:12 | hyperglass.exceptions:38 | __init__ → [WARNING]

Field: vrfs → ipv6 → source_address
  Error: value is not a valid IPv6 address

Traceback (most recent call last):
  File "/usr/local/bin/hyperglass", line 8, in <module>
    sys.exit(CLI())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/cli/commands.py", line 70, in build_frontend
    return build_ui(timeout)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/cli/util.py", line 68, in build_ui
    from hyperglass.configuration import CONFIG_PATH, params, frontend_params
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/__init__.py", line 4, in <module>
    from .main import (
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/main.py", line 144, in <module>
    devices = validate_config(config=_user_devices.get("routers", []), importer=Devices)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/validation.py", line 48, in validate_config
    raise ConfigInvalid(err.errors()) from None
hyperglass.exceptions.ConfigInvalid:

Field: vrfs → ipv6 → source_address
  Error: value is not a valid IPv6 address
```

**Error when IPv6 does not have quotes (no CIDR)**

```
[ERROR] 20210329 03:40:14 | hyperglass.exceptions:38 | __init__ → [WARNING] mapping values are not allowed here
  in "/etc/hyperglass/devices.yaml", line 18, column 41
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/main.py", line 89, in _config_required
    config = yaml.safe_load(cf)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/etc/hyperglass/devices.yaml", line 18, column 41

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hyperglass", line 8, in <module>
    sys.exit(CLI())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/cli/commands.py", line 70, in build_frontend
    return build_ui(timeout)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/cli/util.py", line 68, in build_ui
    from hyperglass.configuration import CONFIG_PATH, params, frontend_params
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/__init__.py", line 4, in <module>
    from .main import (
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/main.py", line 142, in <module>
    _user_devices = _config_required(CONFIG_DEVICES)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/main.py", line 92, in _config_required
    raise ConfigError(str(yaml_error))
hyperglass.exceptions.ConfigError: mapping values are not allowed here
  in "/etc/hyperglass/devices.yaml", line 18, column 41
```

# Steps to Reproduce

## Local Configurations

**Not working, in CIDR**

```
routers:
  - name: Chicago, IL
    address: 10.X.X.3
    network:
      name: production
      display_name: AS2XXXX
    credential:
      username: username
      password: password
    port: 2222
    nos: mikrotik_routeros
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 169.169.169.169
        ipv6:
          source_address: 0000:0000:0000::/64
```

**Not working, no quotes**

```
routers:
  - name: Chicago, IL
    address: 10.X.X.3
    network:
      name: production
      display_name: AS2XXXX
    credential:
      username: username
      password: password
    port: 2222
    nos: mikrotik_routeros
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 169.169.169.169
        ipv6:
          source_address: 0000:0000:0000::
```

**Working configuration**

```
routers:
  - name: Chicago, IL
    address: 10.X.X.3
    network:
      name: production
      display_name: AS2XXXX
    credential:
      username: username
      password: password
    port: 2222
    nos: mikrotik_routeros
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 169.169.169.169
        ipv6:
          source_address: "0000:0000:0000::"
```

## Logs

**See above error messages**

# Possible Solution

Notate in the [documents](https://hyperglass.io/docs/adding-devices#ipv6) that quotes around an IPv6 address is required.

# Environment

## Server

```
| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.80** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.8.5` |
| **Platform Info** | `Linux-5.4.0-70-generic-x86_64-with-glibc2.29` |
| **CPU Info** | Intel Core Processor (Haswell, no TSX, IBRS) |
| **Logical Cores** | `1` |
| **Physical Cores** | `1` |
| **Processor Speed** | 2.399982GHz |
| **Total Memory** | 1.03 GB |
| **Memory Utilization** | 30.6% |
| **Total Disk Space** | 25.14 GB |
| **Disk Utilization** | 21.5% |
```

## Client

**NA**

### Smartphone Details (if applicable)

**NA**

**Comment by checktheroads** [comment]
Thanks, this has been merged.
