### ISSUE TITLE
BGP route with Private networks error

### ISSUE THREAD

**Issue by 3xh4l3** [checktheroads/hyperglass#46]
## Information

**Describe the bug**
An exception occurs when I try to execute the bgp route command with private addresses as an argument

**To Reproduce**
1. Select device
2. Select command BGP route
3. Set target with something from private addresses (192.168..., 172.16... etc.)
4. Execute

**Expected behavior**
Show BGP RIB from device

## Environment

Python 3.7.3
hyperglass    1.0.0b39

**Additional context**
Here is exception which rises

```
[DEBUG] 20200617 03:38:38 | hyperglass.execution.construct:36 | __init__ → Constructing bgp_route query for 'None'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 140, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 133, in app
    raw_response = await dependant.call(**values)
  File "/usr/local/lib/python3.7/dist-packages/hyperglass/api/routes.py", line 83, in query
    cache_output = await Execute(query_data).response()
  File "/usr/local/lib/python3.7/dist-packages/hyperglass/execution/execute.py", line 429, in response
    connect = Connect(device, self.query_data, transport)
  File "/usr/local/lib/python3.7/dist-packages/hyperglass/execution/execute.py", line 66, in __init__
    self._query = Construct(device=self.device, query_data=self.query_data)
  File "/usr/local/lib/python3.7/dist-packages/hyperglass/execution/construct.py", line 60, in __init__
    self.query_data.query_vrf.ipv6,
  File "/usr/local/lib/python3.7/dist-packages/hyperglass/execution/construct.py", line 62, in <listcomp>
    if v is not None and self.query_data.query_target.version == v.version
AttributeError: 'NoneType' object has no attribute 'version'
```

**Comment by 3xh4l3** [comment]
Additional output for query `172.16.1.1`

```
[DEBUG] 20200617 03:49:34 | hyperglass.api.models.query:218 | validate_query_target → {'query_location': 'router_dc1', 'query_type': 'bgp_route', 'query_vrf': Vrf(name='default', display_name='Global', info=Info(bgp_aspath=InfoConfig(enable=True, file=None, params=InfoConfigPa
rams(title=None)), bgp_community=InfoConfig(enable=True, file=None, params=InfoConfigParams(title=None)), bgp_route=InfoConfig(enable=True, file=None, params=InfoConfigParams(title=None)), ping=InfoConfig(enable=True, file=None, params=InfoConfigParams(title=None)), tracero
ute=InfoConfig(enable=True, file=None, params=InfoConfigParams(title=None))), ipv4=DeviceVrf4(source_address=IPv4Address('100.100.100.100'), access_list=[AccessList4(network=IPv4Network('0.0.0.0/0'), action='permit', ge=0, le=32)], force_cidr=True, protocol='ipv4_default', 
version=4), ipv6=None)}
[DEBUG] 20200617 03:49:34 | hyperglass.api.models.validators:24 | _member_of → Checking membership of 172.16.1.1/32 for 0.0.0.0/0
[DEBUG] 20200617 03:49:34 | hyperglass.api.models.validators:31 | _member_of → 172.16.1.1/32 is a member of 0.0.0.0/0
[DEBUG] 20200617 03:49:34 | hyperglass.api.models.validators:109 | validate_ip → 172.16.1.1/32 is allowed by access-list AccessList4(network=IPv4Network('0.0.0.0/0'), action='permit', ge=0, le=32)
[DEBUG] 20200617 03:49:34 | hyperglass.external._base:124 | _test → Testing connection to https://stat.ripe.net
[DEBUG] 20200617 03:49:34 | hyperglass.external._base:85 | __enter__ → Initialized session with https://stat.ripe.net
[DEBUG] 20200617 03:49:34 | hyperglass.external.ripestat:30 | network_info_sync → IP 172.16.1.1 is not a global address
[DEBUG] 20200617 03:49:34 | hyperglass.api.models.validators:152 | validate_ip → Validation passed for 172.16.1.1
[DEBUG] 20200617 03:49:34 | hyperglass.external._base:139 | _atest → Testing connection to https://stat.ripe.net
[DEBUG] 20200617 03:49:34 | hyperglass.external._base:68 | __aenter__ → Initialized session with https://stat.ripe.net
[DEBUG] 20200617 03:49:34 | hyperglass.external.ripestat:60 | network_info → IP 10.6.154.1 is not a global address
[DEBUG] 20200617 03:49:34 | hyperglass.external._base:75 | __aexit__ → Closing session with https://stat.ripe.net
[DEBUG] 20200617 03:49:34 | hyperglass.api.routes:49 | query → Initialized cache ConfigCache(db=0, host=192.168.69.40, port=6379)
[DEBUG] 20200617 03:49:34 | hyperglass.api.routes:58 | query → Cache Timeout: 120
[INFO] 20200617 03:49:34 | hyperglass.api.routes:59 | query → Starting query execution for query Query(query_location=abk_dc1, query_type=bgp_route, query_vrf=default, query_target=None)
```

Why query_target was set to None?

**Comment by checktheroads** [comment]
Hi there,

Sorry for the long delay. I think I _may_ have fixed this, accidentally. In either case, I can't reproduce it in the latest 1.0.0-beta45. Can you give it a go, and let me know if it's still broken for you? If it is, can you share your `devices.yaml` and `hyperglass.yaml`?

Thanks,
Matt

**Comment by checktheroads** [comment]
This should be fixed at least as of 1.0.0-beta.45, if not 1.0.0-beta.49. If the issue remains, please re-open this.
