### ISSUE TITLE
Install script: Please verify all requirements are met before trying to use them

### ISSUE THREAD

**Issue by samip5** [checktheroads/hyperglass#49]
Hi!

I was installing on a Ubuntu 20.04 LXC container, and it DOES not have a lot of the required components installed by default, like `curl`, `git` so maybe check if those are available before trying to use them.

```
[ERROR] Tried to install Redis, but post-install check failed.
Cleaning up temporary files...
[SUCCESS] Finished installed dependencies.
[INFO] Installing hyperglass...
main: line 433: git: command not found
```

**Comment by samip5** [comment]
More errors:

```
root@lg:~# curl https://install.hyperglass.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13291  100 13291    0     0  16449      0 --:--:-- --:--:-- --:--:-- 16428
[INFO] Your system is running Python 3.8.2 (Minimum is 3.6+).
[INFO] Your system is running NodeJS v14.5.0 (Minimum is 14+).
[INFO] Your system is running Yarn 1.22.4 (Minimum is 1+).
[INFO] Your system is running Redis 5.0.7 (Minimum is 4+).
Cleaning up temporary files...
[SUCCESS] Finished installed dependencies.
[INFO] Installing hyperglass...
Cloning into '/tmp/hyperglass'...
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (320/320), done.
remote: Compressing objects: 100% (299/299), done.
remote: Total 320 (delta 11), reused 142 (delta 8), pack-reused 0
Receiving objects: 100% (320/320), 1.06 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Traceback (most recent call last):
  File "/root/.poetry/bin/poetry", line 16, in <module>
    from poetry.console import main
  File "/root/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/root/.poetry/lib/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/root/.poetry/lib/poetry/console/commands/__init__.py", line 15, in <module>
    from .shell import ShellCommand
  File "/root/.poetry/lib/poetry/console/commands/shell.py", line 3, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
```
