### ISSUE TITLE
Error when run hyperglass start

### ISSUE THREAD

**Issue by makanbaks0** [checktheroads/hyperglass#76]
Hi I got an error when run `hyperglass start` after edited `device.yaml`.

I just copied script from `https://hyperglass.io/docs/adding-devices`
```
---
routers:
  - name: test
    address: 10.0.0.1
    network: AS123
    credential:
      username: username
      password: password
    location: pop01
    display_name: ro-1
    port: 22
    nos: huawei
    vrfs:
      - name: default
        ipv4:
          source_address: 10.0.0.1
        ipv6:
          source_address: 2001:db8::1
```
here's the error:
```
[ERROR] 20200916 06:46:36 | hyperglass.configuration:155 | _validate_config → 1 validation error for Device
network
  value is not a valid dict (type=type_error.dict)
[ERROR] 20200916 06:46:36 | hyperglass.exceptions:28 | __init__ → [WARNING]

Field: network
  Error: value is not a valid dict

Traceback (most recent call last):
  File "/usr/local/bin/hyperglass", line 8, in <module>
    sys.exit(CLI())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/cli/commands.py", line 99, in start
    from hyperglass.main import start
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/main.py", line 22, in <module>
    from hyperglass.configuration import (  # isort:skip
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/__init__.py", line 186, in <module>
    devices = _validate_config(config=_user_devices.get("routers", []), importer=Devices)
  File "/usr/local/lib/python3.8/dist-packages/hyperglass/configuration/__init__.py", line 156, in _validate_config
    raise ConfigInvalid(err.errors()) from None
hyperglass.exceptions.ConfigInvalid:

Field: network
  Error: value is not a valid dict
```

Any advice?

Thanks.

**Comment by makanbaks0** [comment]
it work after I change it to:
```
routers:
  # HTTP/hyperglass-agent device
  - name: router01
    display_name: HTTP Router
    address: 192.0.2.1
    network:
      name: primary
      display_name: AS65000
    credential:
      username: madeup
      password: txeTTIqwhKSJi4V3tefXQASf5AyGZ6cPsycS9nYLpKk
    ssl:
      enable: true
      cert: /etc/hyperglass/certs/router01.pem
    port: 8080
    nos: frr
    vrfs:
      - name: default
        ipv4:
          source_address: 192.0.2.1
          access_list:
            - network: 10.0.0.0/8
              action: deny
              ge: 8
              le: 32
            - network: 0.0.0.0/0
              action: permit
              le: 24 # Only allow /24 or smaller prefixes
        ipv6:
          source_address: 2001:db8::1
          access_list:
            - network: ::/0
              action: permit
    proxy: null
```
