### ISSUE TITLE
Ping command uses incorrect source

### ISSUE THREAD

**Issue by Gelob** [checktheroads/hyperglass#8]
## Information

**Describe the bug**
In configuration/commands.toml the ping commands reference src_addr_ipv4 and src_addr_ipv6. This results in a KeyError when trying to run the ping command via the webUI. 

**To Reproduce**
Run a ping against any device.

**Expected behavior**
Ping completes without issue

**Screenshots**
```
[D 190722 17:39:39 construct:79] ping inet {target} count 5 source {src_addr_ipv4}
[E 190722 17:39:39 hyperglass:231] Unable to add output to cache: {'location': 'router1', 'type': 'ping', 'target': '4.2.2.2'}
10.1.1.1 - - [22/Jul/2019 17:39:40] "POST /lg HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 544, in __inner
    return obj(*a, **k)
  File "/opt/hyperglass/hyperglass/hyperglass.py", line 203, in hyperglass_main
    cache_value = execute.Execute(lg_data).response()
  File "/opt/hyperglass/hyperglass/command/execute.py", line 296, in response
    "scrape", device_config, self.input_type, self.input_target
  File "/opt/hyperglass/hyperglass/command/execute.py", line 141, in __init__
    self.params = getattr(Construct(device), query_type)(transport, target)
  File "/opt/hyperglass/hyperglass/command/construct.py", line 80, in ping
    fmt_command = conf_command.format(target=target, source=source)
KeyError: 'src_addr_ipv4'
```

## Environment
CentOS 7, Python3.6

**Comment by checktheroads** [comment]
Looks like this is an issue with my example config file and not the code base itself which is always good.

FYI, the `commands.toml` file goes away entirely in the next release (see the develop branch). Although users can still override the default commands, the application doesn’t rely on a default config file to run.
