### ISSUE TITLE
SSH connection to routers requires a password / key based authentication is not supported?

### ISSUE THREAD

**Issue by bastelfreak** [checktheroads/hyperglass#81]
I want to connect hyperglass to a virtual JunOS MX with ssh key authentication. The user that runs the hyperglass service owns a ssh key and it's configured in the ~/.ssh/config.

# Bug Description

The devices.yaml / hyperglass seems to require a password. I tried to omit the password field and also setting it to null, both resulting in the following error:

# Expected behavior

# Steps to Reproduce

## Local Configurations

```
---
routers:
  - name: vmx-lab-in-my-awesome-lab
    address: 10.10.10.10
    network:
      name: primary
      display_name: lab
    credential:
      username: hyperglass
      password: null
    display_name: something else
    port: 22
    nos: juniper_junos
    proxy: null
    vrfs: null
```

## Logs

```
Sep 17 14:20:50 hyperglass python3[16911]: [ERROR] 20200917 14:20:50 | hyperglass.configuration:155 | _validate_config → 2 validation errors for Device
Sep 17 14:20:50 hyperglass python3[16911]: credential -> password
Sep 17 14:20:50 hyperglass python3[16911]: none is not an allowed value (type=type_error.none.not_allowed)
Sep 17 14:20:50 hyperglass python3[16911]: vrfs
Sep 17 14:20:50 hyperglass python3[16911]: 'NoneType' object is not iterable (type=type_error)
Sep 17 14:20:50 hyperglass python3[16911]: [ERROR] 20200917 14:20:50 | hyperglass.exceptions:28 | __init__ → [WARNING]
Sep 17 14:20:50 hyperglass python3[16911]: Field: credential → password
Sep 17 14:20:50 hyperglass python3[16911]: Error: none is not an allowed value
Sep 17 14:20:50 hyperglass python3[16911]: Field: vrfs
Sep 17 14:20:50 hyperglass python3[16911]: Error: 'NoneType' object is not iterable
Sep 17 14:20:50 hyperglass python3[16911]: Traceback (most recent call last):
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/bin/hyperglass", line 11, in <module>
Sep 17 14:20:50 hyperglass python3[16911]: sys.exit(CLI())
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
Sep 17 14:20:50 hyperglass python3[16911]: return self.main(*args, **kwargs)
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/click/core.py", line 782, in main
Sep 17 14:20:50 hyperglass python3[16911]: rv = self.invoke(ctx)
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
Sep 17 14:20:50 hyperglass python3[16911]: return _process_result(sub_ctx.command.invoke(sub_ctx))
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
Sep 17 14:20:50 hyperglass python3[16911]: return ctx.invoke(self.callback, **ctx.params)
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
Sep 17 14:20:50 hyperglass python3[16911]: return callback(*args, **kwargs)
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/hyperglass/cli/commands.py", line 99, in start
Sep 17 14:20:50 hyperglass python3[16911]: from hyperglass.main import start
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/hyperglass/main.py", line 22, in <module>
Sep 17 14:20:50 hyperglass python3[16911]: from hyperglass.configuration import (  # isort:skip
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/hyperglass/configuration/__init__.py", line 186, in <module>
Sep 17 14:20:50 hyperglass python3[16911]: devices = _validate_config(config=_user_devices.get("routers", []), importer=Devices)
Sep 17 14:20:50 hyperglass python3[16911]: File "/opt/hyperglass/virtualenv/lib64/python3.6/site-packages/hyperglass/configuration/__init__.py", line 156, in _validate_config
Sep 17 14:20:50 hyperglass python3[16911]: raise ConfigInvalid(err.errors()) from None
Sep 17 14:20:50 hyperglass python3[16911]: hyperglass.exceptions.ConfigInvalid:
Sep 17 14:20:50 hyperglass python3[16911]: Field: credential → password
Sep 17 14:20:50 hyperglass python3[16911]: Error: none is not an allowed value
Sep 17 14:20:50 hyperglass python3[16911]: Field: vrfs
Sep 17 14:20:50 hyperglass python3[16911]: Error: 'NoneType' object is not iterable
```

(please ignore the vrfs errors, they should not be related)

# Possible Solution

make the password field optional or add an explicit parameter that uses an ssh key? I checked https://hyperglass.io/docs/adding-devices#credential and wasn't able to find information about ssh key authentication

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.57** |
| **hyperglass Path** | `/opt/hyperglass/hyperglass` |
| **Python Version** | `3.6.8` |
| **Platform Info** | `Linux-5.8.9-1.el7.elrepo.x86_64-x86_64-with-centos-7.8.2003-Core` |
| **CPU Info** | Intel Xeon Processor (Skylake, IBRS) |
| **Logical Cores** | `4` |
| **Physical Cores** | `1` |
| **Processor Speed** | 2.095076GHz |
| **Total Memory** | 4.13 GB |
| **Memory Utilization** | 25.2% |
| **Total Disk Space** | 51.65 GB |
| **Disk Utilization** | 13.4% |

**Comment by checktheroads** [comment]
Yes, key auth is currently not supported but will be before 1.0.0 is out of beta.

**Comment by bastelfreak** [comment]
I can verify that your patch works for me :)
