### ISSUE TITLE
ping query type broken in 1.0.0-beta.59 on Junos 19.4R1-S2.2

### ISSUE THREAD

**Issue by bastelfreak** [checktheroads/hyperglass#90]
Hi, since I upgraded to 1.0.0-beta.59, I cannot run the ping query type anymore.

# Bug Description

I start a ping query type to an ip that's reachable from a JunOS virtual MX. hyperglass now displays `Something went wrong.`

# Expected behavior

I expect that a ping works

# Steps to Reproduce

* Setup latest hyperglass
* Download junos VM image
* configure junos with a default route
* tell hyperglass to ping any ip on the VMX

## Local Configurations

I didn't configure anything in the commands.yml. Section from the devices.yaml:

```yaml
---
routers:
- name: ***
  address: ***
  network:
    name: primary
    display_name: ***
  credential:
    username: hyperglass
    password: foobar
  display_name: ***
  port: 22
  nos: juniper
  proxy:
  vrfs:
  - name: default
    display_name: whatsthis
    ipv4:
      source_address: ***
      force_cidr: false
```

## Logs

```
[10/09/20 15:08:14] INFO     Starting query execution for query Que routes.py:87
ry(query_location=***,
query_type=ping, query_vrf=default,
query_target=***)
INFO     Opening connection to           async_driver.py:100
10.92.118.76
INFO     Attempting to acquire    base_network_driver.py:323
`exec` privilege level
INFO     Acquired requested       base_network_driver.py:360
privilege level `exec`
INFO     Connection to 10.92.118.76      async_driver.py:104
opened successfully
[10/09/20 15:08:18] INFO     Closing connection to           async_driver.py:120
***
[2020-10-09 15:08:18 +0000] [19889] [ERROR] Exception in ASGI application
Traceback (most recent call last):
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/applications.py", line 183, in __call__
await super().__call__(scope, receive, send)  # pragma: no cover
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/applications.py", line 102, in __call__
await self.middleware_stack(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/cors.py", line 86, in __call__
await self.simple_response(scope, receive, send, request_headers=headers)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/cors.py", line 142, in simple_response
await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 550, in __call__
await route.handle(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 227, in handle
await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 41, in app
response = await func(request)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/routing.py", line 197, in app
dependant=dependant, values=values, is_coroutine=is_coroutine
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
return await dependant.call(**values)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/api/routes.py", line 120, in query
cache_output = await execute(query_data)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/execution/main.py", line 72, in execute
output = await driver.parsed_response(response)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/execution/drivers/_common.py", line 65, in parsed_response
_output = await coro(commands=self.query, output=response)
TypeError: object str can't be used in 'await' expression
INFO     Attempting to acquire    base_network_driver.py:323
`exec` privilege level
INFO     Acquired requested       base_network_driver.py:360
privilege level `exec`
INFO     Connection to ***      async_driver.py:124
closed successfully

```

# Possible Solution

# Environment

## Server

 
| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.59** |
| **hyperglass Path** | `/opt/hyperglass/hyperglass-server/hyperglass` |
| **Python Version** | `3.6.8` |
| **Platform Info** | `Linux-5.8.9-1.el7.elrepo.x86_64-x86_64-with-centos-7.8.2003-Core` |
| **CPU Info** | Intel Xeon Processor (Skylake, IBRS) |
| **Logical Cores** | `4` |
| **Physical Cores** | `1` |
| **Processor Speed** | 2.095076GHz |
| **Total Memory** | 4.13 GB |
| **Memory Utilization** | 37.6% |
| **Total Disk Space** | 51.65 GB |
| **Disk Utilization** | 18.1% |

**Comment by bastelfreak** [comment]
for reasons I don't know, the debug output has a very strange format with multiple `\n`:

```
Oct 09 15:17:29 lg python3[27180]: DEBUG    Constructed query: ['ping inet    _construct.py:160 
Oct 09 15:17:29 lg python3[27180]: *** count 5 source 
Oct 09 15:17:29 lg python3[27180]: ***'] 
```

however, I'm able to execute the command manual:

```
[hyperglass@lg ~]$ ssh ***
Last login: Fri Oct  9 17:01:29 2020 from ***
--- JUNOS 19.4R1-S2.2 Kernel 64-bit  JNPR-11.0-20200527.8a79409_buil
warning: user "hyperglass" does not have access privileges.

error: Restricted user session.
hyperglass@***> ping inet *** count 5 source *** 
PING *** (***): 56 data bytes
64 bytes from ***: icmp_seq=0 ttl=62 time=0.869 ms
64 bytes from ***: icmp_seq=1 ttl=62 time=0.821 ms
64 bytes from ***: icmp_seq=2 ttl=62 time=1.173 ms
64 bytes from ***: icmp_seq=3 ttl=62 time=0.743 ms
64 bytes from ***: icmp_seq=4 ttl=62 time=0.973 ms

--- *** ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.743/0.916/1.173/0.149 ms

hyperglass@***>
```

**Comment by bastelfreak** [comment]
and I get a very similar error if I try a traceroute:

```
[10/09/20 15:34:49] INFO     Starting query execution for query Que routes.py:87
ry(query_location=***,
query_type=traceroute,
query_vrf=default,
query_target=***)
INFO     Opening connection to           async_driver.py:100
10.92.118.76
INFO     Attempting to acquire    base_network_driver.py:323
`exec` privilege level
[10/09/20 15:34:50] INFO     Acquired requested       base_network_driver.py:360
privilege level `exec`
INFO     Connection to ***      async_driver.py:104
opened successfully
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
File "uvloop/cbhandles.pyx", line 73, in uvloop.loop.Handle._run
File "uvloop/loop.pyx", line 359, in uvloop.loop.Loop._read_from_self
File "uvloop/loop.pyx", line 364, in uvloop.loop.Loop._invoke_signals
File "uvloop/loop.pyx", line 339, in uvloop.loop.Loop._ceval_process_signals
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/execution/main.py", line 33, in handler
raise DeviceTimeout(**exc_args)
hyperglass.exceptions.DeviceTimeout: Error connecting to ***: Request timed out.
[10/09/20 15:35:16] CRITICAL [DANGER] Error connecting to       exceptions.py:30
***: Request timed
out.
[10/09/20 15:35:20] INFO     Closing connection to           async_driver.py:120
***
[2020-10-09 15:35:20 +0000] [828] [ERROR] Exception in ASGI application
Traceback (most recent call last):
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/applications.py", line 183, in __call__
await super().__call__(scope, receive, send)  # pragma: no cover
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/applications.py", line 102, in __call__
await self.middleware_stack(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/cors.py", line 86, in __call__
await self.simple_response(scope, receive, send, request_headers=headers)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/middleware/cors.py", line 142, in simple_response
await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 550, in __call__
await route.handle(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 227, in handle
await self.app(scope, receive, send)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/starlette/routing.py", line 41, in app
response = await func(request)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/routing.py", line 197, in app
dependant=dependant, values=values, is_coroutine=is_coroutine
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
return await dependant.call(**values)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/api/routes.py", line 120, in query
cache_output = await execute(query_data)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/execution/main.py", line 70, in execute
response = await driver.collect()
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/hyperglass/execution/drivers/ssh_scrapli.py", line 98, in collect
log.debug(f'Raw response for command "{query}":\n{raw.result}')
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/driver/async_driver.py", line 82, in __aexit__
await self.close()
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/driver/async_driver.py", line 122, in close
await self.on_close(self)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/driver/core/juniper_junos/async_driver.py", line 44, in junos_on_close
await conn.acquire_priv(desired_priv=conn.default_desired_privilege_level)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/driver/async_network_driver.py", line 124, in acquire_priv
current_prompt = await self.channel.get_prompt()
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/decorators.py", line 92, in decorate
wrapped_func=wrapped_func, args=args, kwargs=kwargs
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/decorators.py", line 247, in asyncio_timeout
wrapped_func(*args, **kwargs), timeout=self.timeout_duration
File "/usr/lib64/python3.6/asyncio/tasks.py", line 358, in wait_for
return fut.result()
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/channel/async_channel.py", line 204, in get_prompt
self._send_return()
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/channel/base_channel.py", line 172, in _send_return
self.transport.write(channel_input=self.comms_return_char)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli/decorators.py", line 328, in requires_open_session_wrapper
return wrapped_func(*args, **kwargs)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/scrapli_asyncssh/transport/asyncssh_.py", line 439, in write
self.stdin.write(channel_input.encode())
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/asyncssh/stream.py", line 302, in write
return self._chan.write(data, self._datatype)
File "/opt/hyperglass/hyperglass-server/virtualenv/lib64/python3.6/site-packages/asyncssh/channel.py", line 836, in write
raise BrokenPipeError('Channel not open for sending')
BrokenPipeError: Channel not open for sending
INFO     Attempting to acquire    base_network_driver.py:323
`exec` privilege level

```

**Comment by bastelfreak** [comment]
thanks! I can verify that pinging works again
